### ISSUE TITLE
Find more webshop platforms

### ISSUE THREAD

**Issue by skolumban-ex** [skolumban-ex/webshops#1]
https://virtocommerce.com/open-source-net-ecommerce-platform

https://www.nopcommerce.com/en

**Comment by dani-mezei** [comment]
.NET:
https://www.simplcommerce.com/
https://grandnode.com/

Js/Ts:
https://medusajs.com/
https://vercel.com/templates/next.js/nextjs-commerce

Out of these 4 I would prefer medusa.

**Comment by efibalogh** [comment]
https://hydrogen.shopify.dev/

**Comment by LeventeBack** [comment]
https://vendure.io/
