### ISSUE TITLE
Stuff to evaluate

### ISSUE THREAD

**Issue by skolumban-ex** [skolumban-ex/webshops#2]
Try to start up 6 of the found systems.

Try to get:
- nr of forks, market share, example sites,
- update frequency, contributor count

Own experience!

**Comment by LeventeBack** [comment]
https://docs.google.com/spreadsheets/d/1tzrL_6uEGOAMY-IELO3I6fHAhsybVnjlqlqxhoEWZJ0/edit?usp=sharing
